language: node_js
script:
- make archive
deploy:
  provider: releases
  api_key:
    secure: ngLaaSeGwnw7XIHQtRfJiiwUNH8clBr5LHAEapgXR6oVCrdeikXd65XbKp3MBVWmwEtRVmuhPKq+LLNkgf7UmVbbWf0iAaX6DF6ctmvMBx6JadtwtdIJA+JYewTA4fFEUrGp+vjR/3TH0Qr1c+UQfpTnBm6tqhAIVQQQgrxx2NoxLw/k9H8W27NvaqAGb1w6xpP3GuQWtyr7ihLIlIYQtRQa7KoLmccy38wxGkUPxVmW2PSjE4KzDNSM3aHVPYCNxfUJryY71pAxZ954BiLmf/kd95ydIJVJiKVJtJSFDl7QT0wT07DuKLs/iofrHrm43c/AgbLQM6onYv6n6QvvLmXNgW4MLMpLuKgtfidFkr6sI+rIWWB/CjObKVkNr2bs9KhkVM6h2D8ytOVaY/XSdJcPBDkRtOp4dN4ljY6KK4fCtpqqRm50RRUNXH3OpxYv+INVKQoSp4zUIcJfdFLgmTSXOiR1OgdFaLk22olOR7IjPK9Nvj0IbDgb+wiHhYGjoFP1JNEpLlk5DQhEewGTsNyIdFmXpLSj3LkbK0awbt75WtiZ5nhukLbdFnOo6w5KuqTQ8/nVIKxcPwXZhATEepcLShVA2vB6YByX8HHI/Aw0gsQJsvhXYvbMPgVhXgzaWCPgYqjgmQMX4NRgNbAiK4kp3Zcu4Ev5Neg9LNWvWAY=
  file: build/HARImporter.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: luckymarmot/Paw-HARImporter
